/*
 * excelFormulaUtilitiesJS v0.9.0
 * https://github.com/joshatjben/excelFormulaUtilitiesJS/
 *
 * Copyright 2011, Josh Bennett
 * licensed under the MIT license.
 * https://github.com/joshatjben/excelFormulaUtilitiesJS/blob/master/LICENSE.txt
 *
 * Some functionality based off of the jquery core lib
 * Copyright 2011, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Based on Ewbi's Go Calc Prototype Excel Formula Parser. [http://ewbi.blogs.com/develops/2004/12/excel_formula_p.html]
 */
(function(){function z(d,b,c){this.value=d;this.type=b;this.subtype=c}function t(){this.items=[];this.add=function(d,b,c){c||(c="");d=new z(d,b,c);this.addRef(d);return d};this.addRef=function(d){this.items.push(d)};this.index=-1;this.reset=function(){this.index=-1};this.BOF=function(){return this.index<=0};this.EOF=function(){return this.index>=this.items.length-1};this.moveNext=function(){if(this.EOF())return!1;this.index+=1;return!0};this.current=function(){if(this.index===-1)return null;return this.items[this.index]};
this.next=function(){if(this.EOF())return null;return this.items[this.index+1]};this.previous=function(){if(this.index<1)return null;return this.items[this.index-1]}}function H(){this.items=[];this.push=function(d){this.items.push(d)};this.pop=function(d){var b=this.items.pop();return new z(d||"",b.type,n)};this.token=function(){return this.items.length>0?this.items[this.items.length-1]:null};this.value=function(){return this.token()?this.token().value.toString():""};this.type=function(){return this.token()?
this.token().type.toString():""};this.subtype=function(){return this.token()?this.token().subtype.toString():""}}function A(d){for(var b=new t,c=new H,g=0,f=function(){return d.substr(g,1)},a="",e=!1,q=!1,h=!1,i=!1,m=/^[1-9]{1}(\.[0-9]+)?E{1}$/;d.length>0;)if(d.substr(0,1)===" ")d=d.substr(1);else{d.substr(0,1)==="="&&(d=d.substr(1));break}for(;!(g>=d.length);)if(e)f()==='"'?d.substr(g+1,1)==='"'?(a+='"',g+=1):(e=!1,b.add(a,j,I),a=""):a+=f(),g+=1;else if(q)f()==="'"?d.substr(g+1,1)==="'"?(a+="'",
g+=1):q=!1:a+=f(),g+=1;else if(h)f()==="]"&&(h=!1),a+=f(),g+=1;else if(i)a+=f(),g+=1,",#NULL!,#DIV/0!,#VALUE!,#REF!,#NAME?,#NUM!,#N/A,".indexOf(","+a+",")!==-1&&(i=!1,b.add(a,j,J),a="");else if("+-".indexOf(f())!==-1&&a.length>1&&a.match(m))a+=f(),g+=1;else if(f()==='"')a.length>0&&(b.add(a,s),a=""),e=!0,g+=1;else if(f()==="'")a.length>0&&(b.add(a,s),a=""),q=!0,g+=1;else if(f()==="[")h=!0,a+=f(),g+=1;else if(f()==="#")a.length>0&&(b.add(a,s),a=""),i=!0,a+=f(),g+=1;else if(f()==="{")a.length>0&&(b.add(a,
s),a=""),c.push(b.add("ARRAY",k,o)),c.push(b.add("ARRAYROW",k,o)),g+=1;else if(f()===";")a.length>0&&(b.add(a,j),a=""),b.addRef(c.pop()),b.add(",",u),c.push(b.add("ARRAYROW",k,o)),g+=1;else if(f()==="}")a.length>0&&(b.add(a,j),a=""),b.addRef(c.pop("ARRAYROWSTOP")),b.addRef(c.pop("ARRAYSTOP")),g+=1;else if(f()===" "){a.length>0&&(b.add(a,j),a="");b.add("",B);for(g+=1;f()===" "&&!(g>=d.length);)g+=1}else",>=,<=,<>,".indexOf(","+d.substr(g,2)+",")!==-1?(a.length>0&&(b.add(a,j),a=""),b.add(d.substr(g,
2),l,v),g+=2):("+-*/^&=><".indexOf(f())!==-1?(a.length>0&&(b.add(a,j),a=""),b.add(f(),l)):"%".indexOf(f())!==-1?(a.length>0&&(b.add(a,j),a=""),b.add(f(),w)):f()==="("?a.length>0?(c.push(b.add(a,k,o)),a=""):c.push(b.add("",r,o)):f()===","?(a.length>0&&(b.add(a,j),a=""),c.type()!==k?b.add(f(),l,K):b.add(f(),u)):f()===")"?(a.length>0&&(b.add(a,j),a=""),b.addRef(c.pop())):a+=f(),g+=1);a.length>0&&b.add(a,j);for(c=new t;b.moveNext();)a=b.current(),a.type.toString()===B?(f=(f=(f=b.BOF()||b.EOF())&&(b.previous().type.toString()===
k&&b.previous().subtype.toString()===n||b.previous().type.toString()===r&&b.previous().subtype.toString()===n||b.previous().type.toString()===j))&&(b.next().type.toString()===k&&b.next().subtype.toString()===o||b.next().type.toString()===r&&b.next().subtype.toString()===o||b.next().type.toString()===j))&&c.add(a.value.toString(),l,L):c.addRef(a);for(;c.moveNext();)if(a=c.current(),a.type.toString()===l&&a.value.toString()==="-")c.BOF()?a.type=C.toString():c.previous().type.toString()===k&&c.previous().subtype.toString()===
n||c.previous().type.toString()===r&&c.previous().subtype.toString()===n||c.previous().type.toString()===w||c.previous().type.toString()===j?a.subtype=x.toString():a.type=C.toString();else if(a.type.toString()===l&&a.value.toString()==="+")c.BOF()?a.type=y.toString():c.previous().type.toString()===k&&c.previous().subtype.toString()===n||c.previous().type.toString()===r&&c.previous().subtype.toString()===n||c.previous().type.toString()===w||c.previous().type.toString()===j?a.subtype=x.toString():a.type=
y.toString();else if(a.type.toString()===l&&a.subtype.length===0)a.subtype="<>=".indexOf(a.value.substr(0,1))!==-1?v.toString():a.value.toString()==="&"?M.toString():x.toString();else if(a.type.toString()===j&&a.subtype.length===0)a.subtype=isNaN(parseFloat(a.value))?a.value.toString()==="TRUE"||a.value.toString()==="FALSE"?v.toString():N.toString():O.toString();else if(a.type.toString()===k&&a.value.substr(0,1)==="@")a.value=a.value.substr(1).toString();c.reset();for(b=new t;c.moveNext();)c.current().type.toString()!==
y&&b.addRef(c.current());b.reset();return b}var p=window.excelFormulaUtilities=window.excelFormulaUtilities||{},m=window.excelFormulaUtilities.core={};window.excelFormulaUtilities.string=window.excelFormulaUtilities.string||{};var i=window.excelFormulaUtilities.string.formatStr=function(d){for(var b=d,c=1;c<arguments.length;c++)b=b.replace(RegExp("\\{{1}"+(c-1).toString()+"{1}\\}{1}","g"),arguments[c]);return b},D=window.excelFormulaUtilities.string.trim=function(d){return d.replace(/^\s|\s$/,"")};
window.excelFormulaUtilities.string.trim=function(d){return d.replace(/^(?:\s|&nbsp;|<\s*br\s*\/*\s*>)*|(?:\s|&nbsp;|<\s*br\s*\/*\s*>)*$/,"")};if(window.jQuery)m=window.jQuery;else{var P=m.isFunction=function(d){return typeof d==="function"},E=m.isArray=function(d){return typeof d==="object"&&d.length},Q=m.isWindow=function(){return obj&&typeof obj==="object"&&"setInterval"in obj},F=m.isPlainObject=function(d){if(!d||typeof d!=="object"||d.nodeType||Q(d))return!1;if(d.constructor&&!hasOwnProperty.call(d,
"constructor")&&!hasOwnProperty.call(d.constructor.prototype,"isPrototypeOf"))return!1;for(var b in d);return b===void 0||hasOwnProperty.call(d,b)};m.extend=function(){var d,b,c,g,f,a=arguments[0]||{},e=1,q=arguments.length,h=!1;typeof a==="boolean"&&(h=a,a=arguments[1]||{},e=2);typeof a!=="object"&&!P(a)&&(a={});q===e&&(a=this,--e);for(;e<q;e++)if((d=arguments[e])!=null)for(b in d)c=a[b],g=d[b],a!==g&&(h&&g&&(F(g)||(f=E(g)))?(f?(f=!1,c=c&&E(c)?c:[]):c=c&&F(c)?c:{},a[b]=m.extend(h,c,g)):g!==void 0&&
(a[b]=g));return a};var p=window.excelFormulaUtilities=window.excelFormulaUtilities||{},m=window.excelFormulaUtilities.core,i=window.excelFormulaUtilities.string.formatStr,D=window.excelFormulaUtilities.string.trim,h={},y=h.TOK_TYPE_NOOP="noop",j=h.TOK_TYPE_OPERAND="operand",k=h.TOK_TYPE_FUNCTION="function",r=h.TOK_TYPE_SUBEXPR="subexpression",u=h.TOK_TYPE_ARGUMENT="argument",C=h.TOK_TYPE_OP_PRE="operator-prefix",l=h.TOK_TYPE_OP_IN="operator-infix",w=h.TOK_TYPE_OP_POST="operator-postfix",B=h.TOK_TYPE_WSPACE=
"white-space",s=h.TOK_TYPE_UNKNOWN="unknown",o=h.TOK_SUBTYPE_START="start",n=h.TOK_SUBTYPE_STOP="stop",I=h.TOK_SUBTYPE_TEXT="text",O=h.TOK_SUBTYPE_NUMBER="number",v=h.TOK_SUBTYPE_LOGICAL="logical",J=h.TOK_SUBTYPE_ERROR="error",N=h.TOK_SUBTYPE_RANGE="range",x=h.TOK_SUBTYPE_MATH="math",M=h.TOK_SUBTYPE_CONCAT="concatenate",L=h.TOK_SUBTYPE_INTERSECT="intersect",K=h.TOK_SUBTYPE_UNION="union";p.parseFormula=function(d,b){var c=0,g=function(){for(var a="|",b=0;b<c;b+=1)a+="&nbsp;&nbsp;&nbsp;|";return a},
f=document.getElementById(d),a=A(f.value),e="";e+="<table cellspacing='0' style='border-top: 1px #cecece solid; margin-top: 5px; margin-bottom: 5px'>";e+="<tr>";e+="<td class='token' style='font-weight: bold; width: 50px'>index</td>";e+="<td class='token' style='font-weight: bold; width: 125px'>type</td>";e+="<td class='token' style='font-weight: bold; width: 125px'>subtype</td>";e+="<td class='token' style='font-weight: bold; width: 150px'>token</td>";for(e+="<td class='token' style='font-weight: bold; width: 300px'>token tree</td></tr>";a.moveNext();){var h=
a.current();h.subtype===n&&(c-=c>0?1:0);e+="<tr>";e+="<td class='token'>"+(a.index+1)+"</td>";e+="<td class='token'>"+h.type+"</td>";e+="<td class='token'>"+(h.subtype.length===0?"&nbsp;":h.subtype.toString())+"</td>";e+="<td class='token'>"+(h.value.length===0?"&nbsp;":h.value).split(" ").join("&nbsp;")+"</td>";e+="<td class='token'>"+g()+(h.value.length===0?"&nbsp;":h.value).split(" ").join("&nbsp;")+"</td>";e+="</tr>";h.subtype===o&&(c+=1)}e+="</table>";document.getElementById(b).innerHTML=e;f.select();
f.focus()};var R=function(d,b,c,g,f){var a=function(a){return a.replace(/\{\{token\}\}/gi,"{0}").replace(/\{\{autoindent\}\}/gi,"{1}").replace(/\{\{autolinebreak\}\}/gi,"{2}")},e=(d.value.length===0?" ":d.value.toString()).split(" ").join("").toString();if(typeof f==="function"&&(f=f(e,d,c,g),e=f.tokenString,!f.useTemplate))return e;switch(d.type){case "function":switch(d.value){case "ARRAY":e=i(a(b.tmplFunctionStartArray),e,c,g);break;case "ARRAYROW":e=i(a(b.tmplFunctionStartArrayRow),e,c,g);break;
default:e=d.subtype.toString()==="start"?i(a(b.tmplFunctionStart),e,c,g):i(a(b.tmplFunctionStop),e,c,g)}break;case "operand":switch(d.subtype.toString()){case "error":e=i(a(b.tmplOperandError),e,c,g);break;case "range":e=i(a(b.tmplOperandRange),e,c,g);break;case "number":e=i(a(b.tmplOperandNumber),e,c,g);break;case "text":e=i(a(b.tmplOperandText),e,c,g);break;case "argument":e=i(a(b.tmplArgument),e,c,g)}break;case "operator-infix":case "logical":e=i(a(b.tmplOperandLogical),e,c,g);break;case "argument":e=
i(a(b.tmplArgument),e,c,g);break;case "subexpression":e=d.subtype.toString()==="start"?i(a(b.tmplSubexpressionStart),e,c,g):i(a(b.tmplSubexpressionStop),e,c,g)}return e},G=p.formatFormula=function(d,b){for(var c={tmplFunctionStart:"{{autoindent}}{{token}}\n{{autoindent}}(\n",tmplFunctionStop:"\n{{autoindent}}{{token}})",tmplOperandError:"{{token}}",tmplOperandRange:"{{autoindent}}{{token}}",tmplOperandLogical:"{{token}}{{autolinebreak}}",tmplOperandNumber:"{{autoindent}}{{token}}",tmplOperandText:'{{autoindent}}"{{token}}"',
tmplArgument:"{{token}}\n",tmplFunctionStartArray:"",tmplFunctionStartArrayRow:"{",tmplFunctionStopArrayRow:"}",tmplFunctionStopArray:"",tmplSubexpressionStart:"{{autoindent}}(",tmplSubexpressionStop:" )",tmplIndentTab:"\t",tmplIndentSpace:" ",autoLineBreak:"TOK_TYPE_FUNCTION | TOK_TYPE_ARGUMENT | TOK_SUBTYPE_LOGICAL | TOK_TYPE_OP_IN ",newLine:"\n",trim:!0,customTokenRender:null},b=b?m.extend(!0,c,b):c,g=0,c=function(){for(var a="",c=0;c<g;c+=1)a+=b.tmplIndentTab;return a},f=A(d),a="",e=b.autoLineBreak.replace(/\s/gi,
"").split("|"),i=!0,j=function(a){for(var b=0;b<e.length;b+=1)if(a!==null&&typeof a!=="undefined"&&(h[e[b]]===a.type.toString()||h[e[b]]===a.subtype.toString()))return!0;return!1};f.moveNext();){var k=f.current(),l=f.next();k.subtype.toString()===n&&(g-=g>0?1:0);var p=RegExp(b.newLine+"$",""),l=j(l),i=i?c():b.tmplIndentSpace;a+=R(k,b,i,l?b.newLine:"",b.customTokenRender);k.subtype.toString()===o&&(g+=1);i=l||p.test(a)}return b.trim?D(a):a};p.formatFormulaHTML=function(d){return G(d,{tmplFunctionStart:'{{autoindent}}<span class="function">{{token}}</span><br />{{autoindent}}<span class="function_start">(</span><br />',
tmplFunctionStop:'<br />{{autoindent}}{{token}}<span class="function_stop">)</span>',tmplOperandError:"{{token}}",tmplOperandRange:"{{autoindent}}{{token}}",tmplOperandLogical:"{{token}}{{autolinebreak}}",tmplOperandNumber:"{{autoindent}}{{token}}",tmplOperandText:'{{autoindent}}<span class="quote_mark">"</span><span class="text">{{token}}</span><span class="quote_mark">"</span>',tmplArgument:"{{token}}<br />",tmplFunctionStartArray:"",tmplFunctionStartArrayRow:"{",tmplFunctionStopArrayRow:"}",tmplFunctionStopArray:"",
tmplSubexpressionStart:"{{autoindent}}(",tmplSubexpressionStop:" )",tmplIndentTab:'<span class="tabs">&nbsp;&nbsp;&nbsp;&nbsp;</span>',tmplIndentSpace:"&nbsp;",newLine:"<br />",autoLineBreak:"TOK_TYPE_FUNCTION | TOK_TYPE_ARGUMENT | TOK_SUBTYPE_LOGICAL | TOK_TYPE_OP_IN ",trim:!0,customTokenRender:null})};var S=p.formula2CSharp=function(d){var b=[];return G(d,{tmplFunctionStart:"{{token}}(",tmplFunctionStop:"{{token}})",tmplOperandError:"{{token}}",tmplOperandRange:"{{token}}",tmplOperandLogical:"{{token}}",
tmplOperandNumber:"{{token}}",tmplOperandText:'"{{token}}"',tmplArgument:"{{token}}",tmplFunctionStartArray:"",tmplFunctionStartArrayRow:"{",tmplFunctionStopArrayRow:"}",tmplFunctionStopArray:"",tmplSubexpressionStart:"(",tmplSubexpressionStop:")",tmplIndentTab:"\t",tmplIndentSpace:" ",autoLineBreak:"TOK_SUBTYPE_STOP | TOK_SUBTYPE_START | TOK_TYPE_ARGUMENT",trim:!0,customTokenRender:function(c,d){var f="",a={"=":"==","<>":"!=",MIN:"Math.Min",MAX:"Math.Max",ABS:"Math.ABS","&":"+"},e=b[b.length-1],
h=!1;switch(d.type.toString()){case k:switch(d.subtype){case o:/^if$/gi.test(c)?(b.push({name:c,isIf:!0,argumentNumber:0}),f="("):(b.push({name:c,isIf:!1,argumentNumber:0}),f=a[c]||c,h=!0);break;case n:h=!0,e.isIf?(f=")",h=!1):f=a[c]||c,b.pop()}break;case u:if(e.isIf)switch(e.argumentNumber){case 0:f="?";break;case 1:f=":"}else f=a[c]||c,h=!0;e.argumentNumber+=1;break;default:f=a[c]||c,h=!0}return{tokenString:f,useTemplate:h}}})};p.formula2JavaScript=function(d){return S(d)}}})();