// Generated by CoffeeScript 1.3.3
(function() {
  var xl;

  require('./core');

  require('./ExcelFormulaUtilities');

  xl = excelFormulaUtilities;

  module.exports = {
    getTokens: function(f) {
      return xl.getTokens(f).items;
    },
    toJavaScript: function(f) {
      return xl.formula2JavaScript(f);
    }
  };

}).call(this);
